#-----------------------------------------------------------------------------------------------------------------------

ui <- fluidPage(

  titlePanel("Interpopulation Prioritization of Caribou Herds in British Columbia, Canada"),

  sidebarLayout(

    sidebarPanel(

      fluidRow(
        sidebarPanel(
          # Action Button - Calculate Herd Rankings
          actionBttn(inputId = "calculate",
                     label = "Calculate Herd Rankings",
                     style = "jelly",
                     color = "success",
                     size = "sm"),
          tags$br(),
          tags$br(),
          # Action button - Reset Weights
          actionBttn(inputId = "reset",
                     label = "Reset Weights",
                     style = "jelly",
                     color = "warning",
                     size = "sm"),
          width = 12)),

      fluidRow(
        sidebarPanel(
          shinyjs::useShinyjs(),
          id = "side-panel",
          style = "overflow-y:scroll; max-height:650px; position:relative;",
          sliderInput(inputId = "population_size",
                      label = "Population Size",
                      min = 0,
                      max = 100,
                      value = 5,
                      step = 1),
          sliderInput(inputId = "latitude",
                      label = "Latitude",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "distance_from_wg_park",
                      label = "Distance from Wells Gray Park",
                      min = 0,
                      max = 100,
                      value = 5,
                      step = 1),
          sliderInput(inputId = "thlb_propn_protected_total",
                      label = "Proportion of total range with THLB protection",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "thlb_propn_protected_core",
                      label = "Proportion of core range with THLB protection",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "thlb_propn_protected_matrix",
                      label = "Proportion of matrix range with THLB protection",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_total_core",
                      label = "Disturbance (Total Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_total_matrix",
                      label = "Disturbance (Total Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_static_core",
                      label = "Distance (Static Core)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_static_matrix",
                      label = "Disturbance (Static Matrix)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_temporal_core",
                      label = "Disturbance (Temporal Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_temporal_matrix",
                      label = "Disturbance (Temporal Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_agriculture_core",
                      label = "Disturbance (Agricultural Core)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_agriculture_matrix",
                      label = "Disturbance (Agricultural Matrix)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_urban_core",
                      label = "Disturbance (Urban Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_urban_matrix",
                      label = "Disturbance (Urban Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_roadways_core",
                      label = "Disturbance (Roadways Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_roadways_matrix",
                      label = "Disturbance (roadways Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_mining_core",
                      label = "Disturbance (Mining Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_mining_matrix",
                      label = "Disturbance (Mining Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_transmission_core",
                      label = "Disturbance (Transmission Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_transmission_matrix",
                      label = "Disturbance (Transmission Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_cutblock_40_years_core",
                      label = "Disturbance (Cutblock <40 Years Core)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_cutblock_40_years_matrix",
                      label = "Disturbance (Cutblock <40 Years Matrix)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_cutblock_0_10_years_core",
                      label = "Disturbance (Cutblock 0-10 Years Core)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_cutblock_0_10_years_matrix",
                      label = "Disturbance (Cutblock 0-10 Years Matrix)",
                      min = 0,
                      max = 100,
                      value = 10,
                      step = 1),
          sliderInput(inputId = "disturbance_fire_40_years_core",
                      label = "Disturbance (Fire <40 Years Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_fire_40_years_matrix",
                      label = "Disturbance (Fire <40 Years Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_fire_0_10_years_core",
                      label = "Disturbance (Fire 0-10 Years Core)",
                      min = 0,
                      max = 100,
                      value = 5,
                      step = 1),
          sliderInput(inputId = "disturbance_fire_0_10_years_matrix",
                      label = "Disturbance (Fire 0-10 Years Matrix)",
                      min = 0,
                      max = 100,
                      value = 5,
                      step = 1),
          sliderInput(inputId = "disturbance_pests_40_years_core",
                      label = "Disturbance (Pests <40 Years Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_pests_40_years_matrix",
                      label = "Disturbance (Pests <40 Years Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_pests_0_10_years_core",
                      label = "Disturbance (Pests 0-10 Years Core)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          sliderInput(inputId = "disturbance_pests_0_10_years_matrix",
                      label = "Disturbance (Pests 0-10 Years Matrix)",
                      min = 0,
                      max = 100,
                      value = 0,
                      step = 1),
          width = 12)),

      width = 3

    ),

    mainPanel(
      fluidRow(
        tabsetPanel(
          tabPanel("Interactive Map",
                 leafletOutput(outputId = "herds",
                               width = "100%",
                               height = 750)),
          tabPanel("Plot", tags$br(),
                 plotOutput(outputId = "plot",
                            width = "60%",
                            height = 500)),
          tabPanel("Table",
                   tags$br(),
                   DTOutput(outputId = "table",
                            width = "45%",
                            height = 700),
                   tags$br(), tags$br())
      ), align = "center"),

      width = 9

    )
  )
)
